name: fluxnet
channels:
- conda-forge
dependencies:
        - python>3
        - pandas        
        - pytest
        - black
        - geopy
        - geopandas
        - scipy
        - pyjanitor
        - seaborn
        - pip
        - pip:
                - pyffp
