name: fluxnet
channels:
        - conda-forge
dependencies:
        # basics
        - pandas
        - pyjanitor
        - seaborn
        # utilities
        - pytest
        - black
        - tabulate
        - pdfcrop.pl
        - pip
        # geospatial
        - click
        - geopy
        - geopandas
        - cartopy
        - pip:
                  # - pyffp
                  # - geojson
                  # - geojsoncontour
                  - numpy-ext
